services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quizarius
      POSTGRES_PASSWORD: quizarius
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql


